# Generated by Django 4.2.20 on 2025-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mocktest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=0),
        ),
    ]
