# Generated by Django 4.2.20 on 2025-05-10 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votes_choice_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='choices',
            field=models.ManyToManyField(to='polls.choice'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
